#!/usr/bin/env python

import argparse
from json import dump, load
from os.path import dirname, realpath
from sys import exit
from subprocess import call


if __name__ == "__main__":
    base_dir = dirname(realpath(__file__))
    dst = "{0}/current/slideshow.json".format(base_dir)  
    try:
        with open(dst, 'r') as json_file:
            slideshow = load(json_file)
    except IOError:
        exit("Something has gone seriously wrong with the current slideshow directory")

    if slideshow['clear_screen']:
        call('clear')

    d="slide - show slides made with clideshow"
    parser = argparse.ArgumentParser(description=d)
    parser.add_argument('-b', '--back', action='store_true',
                        help="Show the last slide")
    args = parser.parse_args()
    if args.back is None:
        slideshow["current_slide"] -= 1
        print(slideshow["slides"][slideshow["current_slide"]])
    else:
        print(slideshow["slides"][slideshow["current_slide"]])
        slideshow["current_slide"] += 1

    if (slideshow["current_slide"] >= len(slideshow["slides"])
        or slideshow["current_slide"] < 0):
        slideshow["current_slide"] = 0

    with open(dst, 'w') as json_file:
        dump(slideshow, json_file)
