#!/usr/bin/env python

import os
import json
import argparse

if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.realpath(__file__))
    dst = "{0}/current/slideshow.json".format(base_dir)  
    try:
        with open(dst, 'r') as json_file:
            slideshow = json.load(json_file)
    except IOError:
        sys.exit("Something has gone seriously wrong with the current slideshow directory")

    d="slide - show slides made with clideshow"
    parser = argparse.ArgumentParser(description=d)
    parser.add_argument('-b', '--back', action='store_true',
                        help="Show the last slide")
    args = parser.parse_args()
    if args.back is None:
        slideshow["current_slide"] -= 1
        print(slideshow["slides"][slideshow["current_slide"]])
    else:
        print(slideshow["slides"][slideshow["current_slide"]])
        slideshow["current_slide"] += 1

    if (slideshow["current_slide"] >= len(slideshow["slides"])
        or slideshow["current_slide"] < 0):
        slideshow["current_slide"] = 0

    with open(dst, 'w') as json_file:
        json.dump(slideshow, json_file)
